FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY ["Toro.API/Toro.API.csproj", "Toro.API/"]
RUN dotnet restore "Toro.API/Toro.API.csproj"

COPY . .
WORKDIR "/src/Toro.API"
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS runtime
WORKDIR /app
COPY --from=build /app .

EXPOSE 8080

ENTRYPOINT ["dotnet", "Toro.API.dll"]

