// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Toro.Infra.Data.Contexts;

#nullable disable

namespace Toro.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240928213750_AddAccountID")]
    partial class AddAccountID
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Toro.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Balance = 100.0,
                            ClientId = "12454",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false
                        });
                });

            modelBuilder.Entity("Toro.Domain.Entities.BondEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BondAsset")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Index")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Stock")
                        .HasColumnType("float");

                    b.Property<double>("Tax")
                        .HasColumnType("float");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Bonds");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            BondAsset = "CDB",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "IPCA",
                            IssuerName = "Banco Teste",
                            Stock = 100.0,
                            Tax = 5.0,
                            UnitPrice = 1000.0
                        },
                        new
                        {
                            Id = -2,
                            BondAsset = "LCI",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "Pre",
                            IssuerName = "Banco Teste 2",
                            Stock = 100.0,
                            Tax = 5.0,
                            UnitPrice = 2000.0
                        },
                        new
                        {
                            Id = -3,
                            BondAsset = "LCI",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "CDI",
                            IssuerName = "Banco Exemplo",
                            Stock = 200.0,
                            Tax = 4.5,
                            UnitPrice = 1500.0
                        },
                        new
                        {
                            Id = -4,
                            BondAsset = "LCA",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "Selic",
                            IssuerName = "Banco Invest",
                            Stock = 300.0,
                            Tax = 3.7999999999999998,
                            UnitPrice = 1200.0
                        },
                        new
                        {
                            Id = -5,
                            BondAsset = "CDB",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "IPCA",
                            IssuerName = "Banco Alpha",
                            Stock = 150.0,
                            Tax = 6.2000000000000002,
                            UnitPrice = 1000.0
                        },
                        new
                        {
                            Id = -6,
                            BondAsset = "LCI",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "IPCA",
                            IssuerName = "Banco Beta",
                            Stock = 250.0,
                            Tax = 5.5,
                            UnitPrice = 1800.0
                        },
                        new
                        {
                            Id = -7,
                            BondAsset = "Debênture",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "CDI",
                            IssuerName = "Banco Delta",
                            Stock = 80.0,
                            Tax = 7.0,
                            UnitPrice = 2000.0
                        },
                        new
                        {
                            Id = -8,
                            BondAsset = "CRI",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "IPCA",
                            IssuerName = "Banco Gama",
                            Stock = 180.0,
                            Tax = 5.9000000000000004,
                            UnitPrice = 1100.0
                        },
                        new
                        {
                            Id = -9,
                            BondAsset = "CDB",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "Selic",
                            IssuerName = "Banco Omega",
                            Stock = 220.0,
                            Tax = 4.2000000000000002,
                            UnitPrice = 1300.0
                        },
                        new
                        {
                            Id = -10,
                            BondAsset = "LCA",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "CDI",
                            IssuerName = "Banco Theta",
                            Stock = 140.0,
                            Tax = 4.7999999999999998,
                            UnitPrice = 1700.0
                        },
                        new
                        {
                            Id = -11,
                            BondAsset = "LCI",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "IPCA",
                            IssuerName = "Banco Zeta",
                            Stock = 160.0,
                            Tax = 6.0999999999999996,
                            UnitPrice = 1900.0
                        },
                        new
                        {
                            Id = -12,
                            BondAsset = "Debênture",
                            CreateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Deleted = false,
                            Index = "Selic",
                            IssuerName = "Banco Epsilon",
                            Stock = 120.0,
                            Tax = 5.7000000000000002,
                            UnitPrice = 2100.0
                        });
                });

            modelBuilder.Entity("Toro.Domain.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("BondId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BondId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AccountId = 0,
                            BondId = -1,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7570),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7640),
                            Deleted = false,
                            Quantity = 100.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7650)
                        },
                        new
                        {
                            Id = -2,
                            AccountId = 0,
                            BondId = -2,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7650),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7650),
                            Deleted = false,
                            Quantity = 100.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7660)
                        },
                        new
                        {
                            Id = -3,
                            AccountId = 0,
                            BondId = -3,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7660),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7660),
                            Deleted = false,
                            Quantity = 200.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7670)
                        },
                        new
                        {
                            Id = -4,
                            AccountId = 0,
                            BondId = -4,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7670),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7670),
                            Deleted = false,
                            Quantity = 300.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7670)
                        },
                        new
                        {
                            Id = -5,
                            AccountId = 0,
                            BondId = -5,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7680),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7680),
                            Deleted = false,
                            Quantity = 150.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7680)
                        },
                        new
                        {
                            Id = -6,
                            AccountId = 0,
                            BondId = -6,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7680),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7690),
                            Deleted = false,
                            Quantity = 250.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7690)
                        },
                        new
                        {
                            Id = -7,
                            AccountId = 0,
                            BondId = -7,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7690),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7690),
                            Deleted = false,
                            Quantity = 80.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7700)
                        },
                        new
                        {
                            Id = -8,
                            AccountId = 0,
                            BondId = -8,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7700),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7700),
                            Deleted = false,
                            Quantity = 180.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7700)
                        },
                        new
                        {
                            Id = -9,
                            AccountId = 0,
                            BondId = -9,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7710),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7710),
                            Deleted = false,
                            Quantity = 220.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7710)
                        },
                        new
                        {
                            Id = -10,
                            AccountId = 0,
                            BondId = -10,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7720),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7720),
                            Deleted = false,
                            Quantity = 140.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7720)
                        },
                        new
                        {
                            Id = -11,
                            AccountId = 0,
                            BondId = -11,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7730),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7730),
                            Deleted = false,
                            Quantity = 160.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7730)
                        },
                        new
                        {
                            Id = -12,
                            AccountId = 0,
                            BondId = -12,
                            CreateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7730),
                            Date = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7740),
                            Deleted = false,
                            Quantity = 120.0,
                            Status = 2,
                            Type = 0,
                            UpdateDate = new DateTime(2024, 9, 28, 18, 37, 50, 669, DateTimeKind.Local).AddTicks(7740)
                        });
                });

            modelBuilder.Entity("Toro.Domain.Entities.OrderEntity", b =>
                {
                    b.HasOne("Toro.Domain.Entities.AccountEntity", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Toro.Domain.Entities.BondEntity", "Bond")
                        .WithMany("Orders")
                        .HasForeignKey("BondId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Bond");
                });

            modelBuilder.Entity("Toro.Domain.Entities.AccountEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Toro.Domain.Entities.BondEntity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
